# Generated by Django 2.1.7 on 2019-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_teamsport', '0002_auto_20190310_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='contract_ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
