# Generated by Django 2.1.7 on 2019-03-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_teamsport', '0004_opportunity_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
    ]
